### ISSUE TITLE
Humidity calculation error

### ISSUE THREAD

**Issue by boraozgen** [automote/Si7006#1]
Hello,

First of all, great library, thanks. Made the bring-up of my project much easier.

I noticed a problem with the code. When I first flashed the firmware, the temperature values were OK but the humidity value always printed '-6.00'. I checked the library and found out the error was caused by the missing type conversion. When I casted tempHumidity to float before calculation, it worked flawlessly. I actually don't understand how it originally worked without the cast. Full code is below:

```
// Check if humidity is correct by ANDing with 0xFFFE
	if(tempHumidity & 0xFFFE) {
		humidity = (125 * (float)tempHumidity)/65536 - 6;
		return(true);
	}
```

Another issue is that I couldn't manage to read temp and humidity values in the 'No Hold Master Mode'. It says 'Failed to read temperature/humidity' but the I2C returns 0, which means no errors. I have been using 'Hold Master Mode' since then, which works perfectly.

**Comment by lovelesh** [comment]
@boraozgen Thanks for the input. I have made necessary changes and update the library.
